site_name: "Мой персональный сайт"
site_description: "Пример сайта на MkDocs с темой Material"
site_author: "Лейсан"
site_url: "http://127.0.0.1:8000/"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share

nav:
  - Главная: index.md
  - О себе: about.md
  - Проекты: projects.md
  - Контакты: contacts.md